# Auto-generated by tools/find_mangled_morphemes.py — do not edit by hand.
# Each entry blocks a `(L, R)` pair whose concat is a mangled morpheme token in the reference tokenizer:
# concat T = <bound-fragment> + <clean-suffix>, where the bound fragment never appears at word-start AND has no space-prefixed sibling in the vocab.
# Reference tokenizer: /Users/fanzhu/.cache/nanochat-variants/blocked_morphemes/tokenizer
# Mining args: {'reference': '/Users/fanzhu/.cache/nanochat-variants/blocked_morphemes/tokenizer', 'max_chars': 20000000, 'bound_threshold': 0.05, 'min_firings': 1, 'sibling_min_stem_len': 1, 'exclude_blocks_py': ['rustbpe_variants/blocked_morphemes/mined/mangled_climbmix_pass1.py', 'rustbpe_variants/blocked_morphemes/mined/mangled_climbmix_pass2.py']}
# Generated 18 blocks.

BLOCKED_PAIRS = [
    ('ximate', 'ly'),  # → 'ximately' (id=3949, fires=4x); L='ximate' ws_prob=0.000; suffix='ly'
    ('at', 'hered'),  # → 'athered' (id=10440, fires=16x); L='ather' ws_prob=0.000; suffix='ed'
    ('ab', 'led'),  # → 'abled' (id=11076, fires=9x); L='abl' ws_prob=0.041; suffix='ed'
    ('at', 'tered'),  # → 'attered' (id=13140, fires=12x); L='atter' ws_prob=0.000; suffix='ed'
    ('ethe', 'less'),  # → 'etheless' (id=14084, fires=4x); L='ethe' ws_prob=0.000; suffix='less'
    ('oun', 'ter'),  # → 'ounter' (id=14537, fires=17x); L='ount' ws_prob=0.000; suffix='er'
    ('upunct', 'ure'),  # → 'upuncture' (id=18217, fires=15x); L='upunct' ws_prob=0.000; suffix='ure'
    ('atil', 'ity'),  # → 'atility' (id=18967, fires=15x); L='atil' ws_prob=0.000; suffix='ity'
    ('obil', 'es'),  # → 'obiles' (id=19253, fires=2x); L='obil' ws_prob=0.000; suffix='es'
    ('ubil', 'ity'),  # → 'ubility' (id=20400, fires=3x); L='ubil' ws_prob=0.000; suffix='ity'
    ('ymak', 'ers'),  # → 'ymakers' (id=21584, fires=3x); L='ymak' ws_prob=0.000; suffix='ers'
    ('obil', 'ity'),  # → 'obility' (id=26044, fires=9x); L='obil' ws_prob=0.000; suffix='ity'
    ('ot', 'hed'),  # → 'othed' (id=26408, fires=7x); L='oth' ws_prob=0.000; suffix='ed'
    ('om', 'ater'),  # → 'omater' (id=26431, fires=5x); L='omat' ws_prob=0.000; suffix='er'
    ('arry', 'ing'),  # → 'arrying' (id=27165, fires=7x); L='arry' ws_prob=0.000; suffix='ing'
    ('omater', 'ials'),  # → 'omaterials' (id=29781, fires=13x); L='omater' ws_prob=0.000; suffix='ials'
    ('opaus', 'al'),  # → 'opausal' (id=31872, fires=3x); L='opaus' ws_prob=0.000; suffix='al'
    ('y', 'led'),  # → 'yled' (id=32339, fires=3x); L='yl' ws_prob=0.000; suffix='ed'
]
