"""
Tokenizer variant: block mangled-morpheme merges.

Prevents BPE from forming "mangled-morpheme" tokens — composites of the form
`<bound-fragment> + <clean-suffix>` like `'ished'` (= `'ish'`+`'ed'`, splitting
"finished" at fin|ished instead of finish|ed). The hypothesis (see
`rustbpe_variants/blocked_morphemes/README.md`) is that at the nanochat-speedrun
scale, forcing these into `<stem>+<suffix>` 2-token encodings gives the model
better-trained semantic atoms even at a small compression cost.

Reuses the `rustbpe_force_merges` crate purely for its `blocked_pairs=` kwarg.
No SPLIT_PATTERN carve-out (unlike force_merges) and no vocab bump — blocked
merge slots get reallocated by BPE to alternative merges.

Block list at `rustbpe_variants/blocked_morphemes/blocks.py` (generated by
`tools/find_mangled_morphemes.py`; see that module + the variant README for
construction provenance).

Usage:
    uv run python -m wrappers.tok_train_blocked_morphemes
      →  ~/.cache/nanochat-variants/blocked_morphemes/tokenizer/
"""
import runpy
import sys

from wrappers._tokenizer_variant_common import (
    setup_variant_base,
    alias_rustbpe,
    print_downstream_hint,
)


def apply_patches():
    """Install the rustbpe alias + train_from_iterator shim that passes
    BLOCKED_PAIRS. Returns BLOCKED_PAIRS for inspection / testing.

    Must be called AFTER setup_variant_base() and BEFORE any
    nanochat.tokenizer import (so alias_rustbpe wins)."""
    alias_rustbpe("rustbpe_force_merges")

    import nanochat.tokenizer as tk
    from rustbpe_variants.blocked_morphemes.blocks import BLOCKED_PAIRS

    # SPLIT_PATTERN stays pristine (no carve-out for this variant).

    def _patched_train_classmethod(text_iterator, vocab_size):
        """Drop-in replacement that calls rustbpe_force_merges with
        blocked_pairs (and empty forced_pairs — this variant only blocks)."""
        import rustbpe  # aliased to rustbpe_force_merges
        import tiktoken
        from nanochat.tokenizer import SPECIAL_TOKENS

        tokenizer = rustbpe.Tokenizer()
        vocab_size_no_special = vocab_size - len(SPECIAL_TOKENS)
        assert vocab_size_no_special >= 256
        tokenizer.train_from_iterator(
            text_iterator, vocab_size_no_special,
            pattern=tk.SPLIT_PATTERN,
            forced_pairs=[],
            blocked_pairs=BLOCKED_PAIRS,
        )
        pattern = tokenizer.get_pattern()
        mergeable_ranks_list = tokenizer.get_mergeable_ranks()
        # Blocking only removes merge candidates — ids stay dense from 0 (no
        # post-train injection like force_merges does), so the sparse-id guard
        # there isn't needed. Keep a light shortfall warning for small corpora.
        ids = [v for _, v in mergeable_ranks_list]
        n_unique = len(set(ids))
        if n_unique < vocab_size_no_special:
            import warnings
            warnings.warn(
                f"blocked_morphemes produced {n_unique}/{vocab_size_no_special} "
                f"unique merges ({vocab_size_no_special - n_unique} short). "
                f"Likely cause: training corpus too small to fill the vocab. "
                f"Proceeding with reduced vocab.",
                stacklevel=2,
            )
        mergeable_ranks = {bytes(k): v for k, v in mergeable_ranks_list}
        tokens_offset = len(mergeable_ranks)
        special_tokens = {name: tokens_offset + i for i, name in enumerate(SPECIAL_TOKENS)}
        enc = tiktoken.Encoding(
            name="rustbpe_blocked_morphemes",
            pat_str=pattern,
            mergeable_ranks=mergeable_ranks,
            special_tokens=special_tokens,
        )
        return tk.RustBPETokenizer(enc, "<|bos|>")

    tk.RustBPETokenizer.train_from_iterator = classmethod(
        lambda cls, text_iterator, vocab_size: _patched_train_classmethod(text_iterator, vocab_size)
    )
    return BLOCKED_PAIRS


def main():
    variant_base = setup_variant_base("blocked_morphemes")
    blocked = apply_patches()
    from rustbpe_variants.blocked_morphemes.blocks import RECOMMENDED_VOCAB_SIZE

    user_args = sys.argv[1:]
    has_vocab_arg = any(
        a == "--vocab-size" or a.startswith("--vocab-size=")
        for a in user_args
    )
    if has_vocab_arg:
        effective_vocab = "caller-supplied (see --vocab-size in args below)"
    else:
        user_args = ["--vocab-size", str(RECOMMENDED_VOCAB_SIZE)] + user_args
        effective_vocab = f"{RECOMMENDED_VOCAB_SIZE} (nanochat default, no bump)"
    print(f"==> variant_base:    {variant_base}")
    print(f"==> rustbpe module:  {__import__('rustbpe').__file__}")
    print(f"==> SPLIT_PATTERN:   pristine (no carve-out)")
    print(f"==> blocked pairs:   {len(blocked)}")
    print(f"==> vocab_size:      {effective_vocab}")
    print(f"==> tok_train args:  {user_args}")
    sys.argv = ["tok_train.py"] + user_args
    runpy.run_module("scripts.tok_train", run_name="__main__")
    print_downstream_hint(variant_base)


if __name__ == "__main__":
    main()
