# Auto-generated by tools/mine_seed_compositions.py
# Source: adjacent-token-pair bigrams in baseline-tokenizer output
# Baseline tokenizer: /Users/fanzhu/.cache/nanochat/tokenizer
# Mining args: {'baseline': '/Users/fanzhu/.cache/nanochat/tokenizer', 'max_chars': 20000000, 'min_count': 20, 'top_k': 500}
# Each entry: (L_bytes, R_bytes, S_bytes). Both operands are baseline-vocab tokens
# by construction; concat S is NOT in baseline. Wrapper inserts S at rank max(id_L, id_R)+1.
SEED_ROUTES = [
    (b'$', b'*', b'$*'),  # count=28, max_id=42, L_id=36, R_id=42
    (b'.', b'!', b'.!'),  # count=30, max_id=46, L_id=46, R_id=33
    (b'&', b'B', b'&B'),  # count=30, max_id=66, L_id=38, R_id=66
    (b'Y', b'C', b'YC'),  # count=26, max_id=89, L_id=89, R_id=67
    (b'!', b'[', b'!['),  # count=32, max_id=91, L_id=33, R_id=91
    (b',', b'b', b',b'),  # count=24, max_id=98, L_id=44, R_id=98
    (b'I', b'l', b'Il'),  # count=77, max_id=108, L_id=73, R_id=108
    (b'd', b'n', b'dn'),  # count=124, max_id=110, L_id=100, R_id=110
    (b'n', b'l', b'nl'),  # count=122, max_id=110, L_id=110, R_id=108
    (b'n', b'u', b'nu'),  # count=25, max_id=117, L_id=110, R_id=117
    (b'w', b'y', b'wy'),  # count=54, max_id=121, L_id=119, R_id=121
    (b'\x82', b'\xb9', b'\x82\xb9'),  # count=26, max_id=185, L_id=130, R_id=185
    (b'\xe0', b'\xba', b'\xe0\xba'),  # count=68, max_id=224, L_id=224, R_id=186
    (b'\xe2', b'\x90', b'\xe2\x90'),  # count=25, max_id=226, L_id=226, R_id=144
    (b' a', b'H', b' aH'),  # count=29, max_id=257, L_id=257, R_id=72
    (b't', b're', b'tre'),  # count=38, max_id=260, L_id=116, R_id=260
    (b' f', b'i', b' fi'),  # count=28, max_id=278, L_id=278, R_id=105
    (b'k', b'an', b'kan'),  # count=31, max_id=281, L_id=107, R_id=281
    (b'n', b'ar', b'nar'),  # count=34, max_id=286, L_id=110, R_id=286
    (b'b', b'ent', b'bent'),  # count=33, max_id=299, L_id=98, R_id=299
    (b'i', b'om', b'iom'),  # count=41, max_id=304, L_id=105, R_id=304
    (b'om', b'ar', b'omar'),  # count=37, max_id=304, L_id=304, R_id=286
    (b' n', b'g', b' ng'),  # count=24, max_id=309, L_id=309, R_id=103
    (b' T', b'il', b' Til'),  # count=40, max_id=319, L_id=319, R_id=302
    (b' T', b'L', b' TL'),  # count=25, max_id=319, L_id=319, R_id=76
    (b'id', b'ar', b'idar'),  # count=27, max_id=320, L_id=320, R_id=286
    (b'en', b'ol', b'enol'),  # count=25, max_id=322, L_id=269, R_id=322
    (b' I', b'K', b' IK'),  # count=28, max_id=333, L_id=333, R_id=75
    (b' that', b'ch', b' thatch'),  # count=30, max_id=334, L_id=334, R_id=328
    (b'an', b'ay', b'anay'),  # count=57, max_id=341, L_id=281, R_id=341
    (b'p', b'se', b'pse'),  # count=51, max_id=344, L_id=112, R_id=344
    (b'ot', b'if', b'otif'),  # count=73, max_id=345, L_id=317, R_id=345
    (b' d', b'if', b' dif'),  # count=40, max_id=345, L_id=289, R_id=345
    (b' n', b'am', b' nam'),  # count=41, max_id=348, L_id=309, R_id=348
    (b"'", b'est', b"'est"),  # count=57, max_id=350, L_id=39, R_id=350
    (b'ad', b'z', b'adz'),  # count=35, max_id=358, L_id=358, R_id=122
    (b'ter', b're', b'terre'),  # count=105, max_id=361, L_id=361, R_id=260
    (b'ure', b'a', b'urea'),  # count=42, max_id=367, L_id=367, R_id=97
    (b'M', b'ill', b'Mill'),  # count=26, max_id=371, L_id=77, R_id=371
    (b'an', b'um', b'anum'),  # count=59, max_id=375, L_id=281, R_id=375
    (b'it', b'um', b'itum'),  # count=26, max_id=375, L_id=273, R_id=375
    (b'ab', b'b', b'abb'),  # count=38, max_id=377, L_id=377, R_id=98
    (b'ab', b'l', b'abl'),  # count=34, max_id=377, L_id=377, R_id=108
    (b'-', b'ab', b'-ab'),  # count=24, max_id=377, L_id=45, R_id=377
    (b'a', b'qu', b'aqu'),  # count=42, max_id=384, L_id=97, R_id=384
    (b'qu', b'ant', b'quant'),  # count=24, max_id=384, L_id=384, R_id=380
    (b' M', b'ing', b' Ming'),  # count=79, max_id=404, L_id=404, R_id=272
    (b' ne', b'op', b' neop'),  # count=36, max_id=406, L_id=406, R_id=394
    (b'on', b'em', b'onem'),  # count=57, max_id=407, L_id=261, R_id=407
    (b'em', b'us', b'emus'),  # count=50, max_id=407, L_id=407, R_id=305
    (b' (', b'.', b' (.'),  # count=30, max_id=412, L_id=412, R_id=46
    (b'ig', b'ial', b'igial'),  # count=47, max_id=418, L_id=325, R_id=418
    (b' D', b'ed', b' Ded'),  # count=26, max_id=427, L_id=427, R_id=284
    (b' H', b'O', b' HO'),  # count=28, max_id=431, L_id=431, R_id=79
    (b'ab', b'and', b'aband'),  # count=25, max_id=432, L_id=377, R_id=432
    (b'all', b'us', b'allus'),  # count=70, max_id=439, L_id=439, R_id=305
    (b'ould', b'ers', b'oulders'),  # count=26, max_id=450, L_id=450, R_id=378
    (b'f', b'ine', b'fine'),  # count=29, max_id=451, L_id=102, R_id=451
    (b'out', b'ine', b'outine'),  # count=31, max_id=452, L_id=452, R_id=451
    (b'u', b'pt', b'upt'),  # count=29, max_id=454, L_id=117, R_id=454
    (b' b', b'ard', b' bard'),  # count=67, max_id=460, L_id=277, R_id=460
    (b'ard', b'ic', b'ardic'),  # count=31, max_id=460, L_id=460, R_id=290
    (b' R', b'X', b' RX'),  # count=36, max_id=468, L_id=468, R_id=88
    (b']', b'The', b']The'),  # count=32, max_id=483, L_id=93, R_id=483
    (b'oc', b'age', b'ocage'),  # count=28, max_id=485, L_id=436, R_id=485
    (b' L', b'id', b' Lid'),  # count=25, max_id=491, L_id=491, R_id=320
    (b'ag', b'ot', b'agot'),  # count=44, max_id=493, L_id=493, R_id=317
    (b'w', b'ag', b'wag'),  # count=30, max_id=493, L_id=119, R_id=493
    (b'ag', b'and', b'agand'),  # count=29, max_id=493, L_id=493, R_id=432
    (b'-', b'ag', b'-ag'),  # count=24, max_id=493, L_id=45, R_id=493
    (b' G', b'S', b' GS'),  # count=26, max_id=502, L_id=502, R_id=83
    (b'ib', b'i', b'ibi'),  # count=39, max_id=510, L_id=510, R_id=105
    (b'am', b'ib', b'amib'),  # count=34, max_id=510, L_id=348, R_id=510
    (b'ib', b'ar', b'ibar'),  # count=27, max_id=510, L_id=510, R_id=286
    (b'ans', b'i', b'ansi'),  # count=35, max_id=512, L_id=512, R_id=105
    (b'ad', b'ru', b'adru'),  # count=34, max_id=520, L_id=358, R_id=520
    (b' W', b'are', b' Ware'),  # count=24, max_id=526, L_id=373, R_id=526
    (b' sp', b'ay', b' spay'),  # count=25, max_id=541, L_id=541, R_id=341
    (b'ut', b'ations', b'utations'),  # count=44, max_id=545, L_id=316, R_id=545
    (b'ass', b'in', b'assin'),  # count=36, max_id=573, L_id=573, R_id=258
    (b' N', b'ass', b' Nass'),  # count=25, max_id=573, L_id=489, R_id=573
    (b' sc', b'ab', b' scab'),  # count=41, max_id=589, L_id=589, R_id=377
    (b'ild', b'ing', b'ilding'),  # count=25, max_id=593, L_id=593, R_id=272
    (b' ev', b'ans', b' evans'),  # count=35, max_id=599, L_id=599, R_id=512
    (b' hel', b'ical', b' helical'),  # count=31, max_id=617, L_id=617, R_id=443
    (b' Y', b'ach', b' Yach'),  # count=40, max_id=621, L_id=621, R_id=570
    (b' cont', b'row', b' controw'),  # count=36, max_id=632, L_id=503, R_id=632
    (b' do', b'ber', b' dober'),  # count=43, max_id=635, L_id=425, R_id=635
    (b' ar', b'um', b' arum'),  # count=135, max_id=638, L_id=638, R_id=375
    (b' cl', b'ove', b' clove'),  # count=29, max_id=658, L_id=528, R_id=658
    (b' y', b'ang', b' yang'),  # count=28, max_id=660, L_id=308, R_id=660
    (b' tr', b'ance', b' trance'),  # count=40, max_id=684, L_id=684, R_id=532
    (b'ount', b'as', b'ountas'),  # count=28, max_id=686, L_id=686, R_id=294
    (b' r', b'ick', b' rick'),  # count=41, max_id=711, L_id=413, R_id=711
    (b'oth', b'os', b'othos'),  # count=37, max_id=742, L_id=742, R_id=399
    (b' P', b'oth', b' Poth'),  # count=32, max_id=742, L_id=403, R_id=742
    (b' g', b'oss', b' goss'),  # count=40, max_id=756, L_id=312, R_id=756
    (b'oss', b'al', b'ossal'),  # count=28, max_id=756, L_id=756, R_id=280
    (b'ph', b'ag', b'phag'),  # count=44, max_id=759, L_id=759, R_id=493
    (b'ov', b'ens', b'ovens'),  # count=25, max_id=763, L_id=763, R_id=563
    (b' inter', b'le', b' interle'),  # count=25, max_id=791, L_id=791, R_id=292
    (b'r', b'ink', b'rink'),  # count=24, max_id=813, L_id=114, R_id=813
    (b' se', b'ize', b' seize'),  # count=27, max_id=834, L_id=405, R_id=834
    (b'c', b'ade', b'cade'),  # count=25, max_id=839, L_id=99, R_id=839
    (b' ob', b't', b' obt'),  # count=89, max_id=850, L_id=850, R_id=116
    (b'rit', b'a', b'rita'),  # count=24, max_id=851, L_id=851, R_id=97
    (b'ach', b'ts', b'achts'),  # count=42, max_id=856, L_id=570, R_id=856
    (b' inf', b'ar', b' infar'),  # count=28, max_id=864, L_id=864, R_id=286
    (b' det', b'on', b' deton'),  # count=24, max_id=871, L_id=871, R_id=261
    (b' ass', b'ass', b' assass'),  # count=44, max_id=875, L_id=875, R_id=573
    (b' re', b'ins', b' reins'),  # count=31, max_id=901, L_id=303, R_id=901
    (b'in', b'vent', b'invent'),  # count=53, max_id=918, L_id=258, R_id=918
    (b'vent', b'ory', b'ventory'),  # count=52, max_id=918, L_id=918, R_id=695
    (b' Wh', b'or', b' Whor'),  # count=56, max_id=931, L_id=931, R_id=276
    (b'et', b'ian', b'etian'),  # count=32, max_id=940, L_id=310, R_id=940
    (b'oc', b'ages', b'ocages'),  # count=40, max_id=1017, L_id=436, R_id=1017
    (b' cor', b'p', b' corp'),  # count=53, max_id=1033, L_id=1033, R_id=112
    (b'ick', b'ets', b'ickets'),  # count=38, max_id=1066, L_id=711, R_id=1066
    (b'we', b'ather', b'weather'),  # count=39, max_id=1068, L_id=677, R_id=1068
    (b'ather', b'ing', b'athering'),  # count=25, max_id=1068, L_id=1068, R_id=272
    (b'cl', b'ists', b'clists'),  # count=26, max_id=1071, L_id=1071, R_id=986
    (b'aw', b'ks', b'awks'),  # count=37, max_id=1074, L_id=1074, R_id=507
    (b' R', b'ew', b' Rew'),  # count=25, max_id=1079, L_id=468, R_id=1079
    (b' vis', b'or', b' visor'),  # count=31, max_id=1081, L_id=1081, R_id=276
    (b'ien', b'se', b'iense'),  # count=45, max_id=1093, L_id=1093, R_id=344
    (b'ov', b'ium', b'ovium'),  # count=25, max_id=1102, L_id=763, R_id=1102
    (b'ars', b'on', b'arson'),  # count=56, max_id=1123, L_id=1123, R_id=261
    (b'ot', b'ars', b'otars'),  # count=44, max_id=1123, L_id=317, R_id=1123
    (b' S', b'ier', b' Sier'),  # count=35, max_id=1139, L_id=349, R_id=1139
    (b'ier', b'ad', b'ierad'),  # count=34, max_id=1139, L_id=1139, R_id=358
    (b" '", b'(', b" '("),  # count=34, max_id=1140, L_id=1140, R_id=40
    (b'or', b'led', b'orled'),  # count=58, max_id=1172, L_id=276, R_id=1172
    (b'pl', b'ash', b'plash'),  # count=31, max_id=1207, L_id=488, R_id=1207
    (b'ar', b'ash', b'arash'),  # count=30, max_id=1207, L_id=286, R_id=1207
    (b' Th', b'i', b' Thi'),  # count=31, max_id=1223, L_id=1223, R_id=105
    (b'und', b'i', b'undi'),  # count=30, max_id=1236, L_id=1236, R_id=105
    (b'ram', b'und', b'ramund'),  # count=28, max_id=1236, L_id=821, R_id=1236
    (b'pr', b'ice', b'price'),  # count=42, max_id=1419, L_id=1419, R_id=566
    (b'est', b'ination', b'estination'),  # count=26, max_id=1436, L_id=350, R_id=1436
    (b' Ar', b'um', b' Arum'),  # count=71, max_id=1508, L_id=1508, R_id=375
    (b' v', b'ane', b' vane'),  # count=29, max_id=1523, L_id=392, R_id=1523
    (b'cc', b'ane', b'ccane'),  # count=25, max_id=1523, L_id=529, R_id=1523
    (b' par', b'ter', b' parter'),  # count=110, max_id=1528, L_id=1528, R_id=361
    (b'it', b'ems', b'items'),  # count=33, max_id=1619, L_id=273, R_id=1619
    (b'm', b'ode', b'mode'),  # count=46, max_id=1646, L_id=109, R_id=1646
    (b' hist', b'one', b' histone'),  # count=31, max_id=1647, L_id=1647, R_id=551
    (b'ass', b'au', b'assau'),  # count=34, max_id=1679, L_id=573, R_id=1679
    (b' non', b'w', b' nonw'),  # count=26, max_id=1694, L_id=1694, R_id=119
    (b' C', b'ott', b' Cott'),  # count=35, max_id=1708, L_id=359, R_id=1708
    (b'ott', b'ont', b'ottont'),  # count=32, max_id=1708, L_id=1708, R_id=1197
    (b'r', b'oring', b'roring'),  # count=28, max_id=1710, L_id=114, R_id=1710
    (b'aster', b'y', b'astery'),  # count=52, max_id=1717, L_id=1717, R_id=121
    (b' mon', b'aster', b' monaster'),  # count=35, max_id=1717, L_id=1048, R_id=1717
    (b'aster', b'ies', b'asteries'),  # count=26, max_id=1717, L_id=1717, R_id=391
    (b' st', b'ables', b' stables'),  # count=32, max_id=1718, L_id=332, R_id=1718
    (b'ah', b'aw', b'ahaw'),  # count=32, max_id=1766, L_id=1766, R_id=1074
    (b' me', b'jor', b' mejor'),  # count=38, max_id=1793, L_id=522, R_id=1793
    (b' mach', b'ined', b' machined'),  # count=27, max_id=1796, L_id=1796, R_id=1280
    (b' pr', b'onom', b' pronom'),  # count=31, max_id=1831, L_id=762, R_id=1831
    (b'onom', b'inal', b'onominal'),  # count=29, max_id=1831, L_id=1831, R_id=1257
    (b' At', b'g', b' Atg'),  # count=40, max_id=1834, L_id=1834, R_id=103
    (b' Se', b'ah', b' Seah'),  # count=33, max_id=1837, L_id=1837, R_id=1766
    (b' Se', b'ab', b' Seab'),  # count=28, max_id=1837, L_id=1837, R_id=377
    (b've', b'ctor', b'vector'),  # count=54, max_id=1838, L_id=301, R_id=1838
    (b' ste', b'ers', b' steers'),  # count=31, max_id=1848, L_id=1848, R_id=378
    (b'ret', b'ions', b'retions'),  # count=28, max_id=1850, L_id=1850, R_id=462
    (b'-m', b'ot', b'-mot'),  # count=75, max_id=1861, L_id=1861, R_id=317
    (b' [', b'(', b' [('),  # count=34, max_id=1906, L_id=1906, R_id=40
    (b' C', b'ray', b' Cray'),  # count=30, max_id=2044, L_id=359, R_id=2044
    (b' stop', b'per', b' stopper'),  # count=52, max_id=2101, L_id=2101, R_id=435
    (b'com', b'ment', b'comment'),  # count=35, max_id=2123, L_id=2123, R_id=390
    (b' purp', b'ure', b' purpure'),  # count=31, max_id=2144, L_id=2144, R_id=367
    (b'-d', b'ried', b'-dried'),  # count=24, max_id=2165, L_id=1623, R_id=2165
    (b' P', b'itch', b' Pitch'),  # count=27, max_id=2176, L_id=403, R_id=2176
    (b'ber', b'man', b'berman'),  # count=39, max_id=2228, L_id=635, R_id=2228
    (b' Ear', b'l', b' Earl'),  # count=27, max_id=2253, L_id=2253, R_id=108
    (b't', b'use', b'tuse'),  # count=163, max_id=2272, L_id=116, R_id=2272
    (b'ar', b'gar', b'argar'),  # count=35, max_id=2306, L_id=286, R_id=2306
    (b's', b'elling', b'selling'),  # count=24, max_id=2581, L_id=115, R_id=2581
    (b'b', b'augh', b'baugh'),  # count=74, max_id=2614, L_id=98, R_id=2614
    (b' H', b'AT', b' HAT'),  # count=37, max_id=2658, L_id=431, R_id=2658
    (b' bott', b'ling', b' bottling'),  # count=29, max_id=2740, L_id=2740, R_id=1413
    (b' load', b'er', b' loader'),  # count=25, max_id=2829, L_id=2829, R_id=263
    (b' Man', b'ning', b' Manning'),  # count=35, max_id=2846, L_id=2846, R_id=707
    (b' Am', b'mon', b' Ammon'),  # count=24, max_id=2852, L_id=2852, R_id=2729
    (b' Pr', b'an', b' Pran'),  # count=39, max_id=2882, L_id=2882, R_id=281
    (b' Pr', b'uss', b' Pruss'),  # count=31, max_id=2882, L_id=2882, R_id=1494
    (b' z', b'oon', b' zoon'),  # count=50, max_id=2888, L_id=1706, R_id=2888
    (b' p', b'illing', b' pilling'),  # count=29, max_id=2905, L_id=275, R_id=2905
    (b' aut', b'oph', b' autoph'),  # count=328, max_id=2949, L_id=1064, R_id=2949
    (b'oph', b'all', b'ophall'),  # count=70, max_id=2949, L_id=2949, R_id=439
    (b'oph', b'ag', b'ophag'),  # count=30, max_id=2949, L_id=2949, R_id=493
    (b'reg', b'ulation', b'regulation'),  # count=24, max_id=2990, L_id=2990, R_id=1274
    (b'nal', b'ist', b'nalist'),  # count=26, max_id=3008, L_id=3008, R_id=400
    (b'-h', b'ah', b'-hah'),  # count=27, max_id=3011, L_id=3011, R_id=1766
    (b' calcul', b'ators', b' calculators'),  # count=30, max_id=3100, L_id=3100, R_id=1855
    (b' Austral', b'op', b' Australop'),  # count=36, max_id=3236, L_id=3236, R_id=394
    (b' Sh', b'ields', b' Shields'),  # count=37, max_id=3371, L_id=1607, R_id=3371
    (b' ver', b'bs', b' verbs'),  # count=45, max_id=3402, L_id=3402, R_id=1210
    (b'per', b'mat', b'permat'),  # count=30, max_id=3410, L_id=435, R_id=3410
    (b' sent', b'it', b' sentit'),  # count=28, max_id=3480, L_id=3480, R_id=273
    (b'hel', b'ia', b'helia'),  # count=25, max_id=3490, L_id=3490, R_id=604
    (b' Gl', b'oss', b' Gloss'),  # count=28, max_id=3513, L_id=3513, R_id=756
    (b'And', b'rew', b'Andrew'),  # count=39, max_id=3527, L_id=3495, R_id=3527
    (b' lat', b'us', b' latus'),  # count=54, max_id=3561, L_id=3561, R_id=305
    (b'and', b'ha', b'andha'),  # count=28, max_id=3570, L_id=432, R_id=3570
    (b' demand', b'er', b' demander'),  # count=54, max_id=3607, L_id=3607, R_id=263
    (b' paint', b'ball', b' paintball'),  # count=27, max_id=3616, L_id=3616, R_id=3408
    (b'bor', b'hood', b'borhood'),  # count=25, max_id=3666, L_id=3666, R_id=3364
    (b' Em', b'ory', b' Emory'),  # count=27, max_id=3685, L_id=3685, R_id=695
    (b' code', b'book', b' codebook'),  # count=31, max_id=3742, L_id=2825, R_id=3742
    (b' flavor', b'ings', b' flavorings'),  # count=25, max_id=3747, L_id=3747, R_id=633
    (b' #', b'#', b' ##'),  # count=114, max_id=3758, L_id=3758, R_id=35
    (b'omb', b'us', b'ombus'),  # count=29, max_id=3763, L_id=3763, R_id=305
    (b'ray', b'fish', b'rayfish'),  # count=28, max_id=3805, L_id=2044, R_id=3805
    (b' try', b'pan', b' trypan'),  # count=72, max_id=3841, L_id=1409, R_id=3841
    (b'pan', b'os', b'panos'),  # count=27, max_id=3841, L_id=3841, R_id=399
    (b' tri', b'pe', b' tripe'),  # count=25, max_id=3852, L_id=3852, R_id=382
    (b' tit', b'an', b' titan'),  # count=144, max_id=3950, L_id=3950, R_id=281
    (b' fly', b'ers', b' flyers'),  # count=69, max_id=4017, L_id=4017, R_id=378
    (b' fly', b'er', b' flyer'),  # count=29, max_id=4017, L_id=4017, R_id=263
    (b'R', b'AM', b'RAM'),  # count=36, max_id=4034, L_id=82, R_id=4034
    (b'D', b'\xc3\xa9', b'D\xc3\xa9'),  # count=41, max_id=4043, L_id=68, R_id=4043
    (b'key', b'e', b'keye'),  # count=30, max_id=4090, L_id=4090, R_id=101
    (b've', b'ctors', b'vectors'),  # count=32, max_id=4093, L_id=301, R_id=4093
    (b'che', b'ap', b'cheap'),  # count=33, max_id=4095, L_id=4095, R_id=574
    (b' S', b'EM', b' SEM'),  # count=25, max_id=4116, L_id=349, R_id=4116
    (b' Mon', b'aster', b' Monaster'),  # count=43, max_id=4156, L_id=4156, R_id=1717
    (b'-qu', b'ad', b'-quad'),  # count=35, max_id=4244, L_id=4244, R_id=358
    (b' nan', b'oc', b' nanoc'),  # count=80, max_id=4324, L_id=4324, R_id=436
    (b' p', b'unk', b' punk'),  # count=26, max_id=4330, L_id=275, R_id=4330
    (b' leaf', b'let', b' leaflet'),  # count=32, max_id=4374, L_id=4374, R_id=1636
    (b' flav', b'oring', b' flavoring'),  # count=34, max_id=4379, L_id=4379, R_id=1710
    (b' neut', b'ering', b' neutering'),  # count=36, max_id=4388, L_id=4388, R_id=1249
    (b'ident', b'ifying', b'identifying'),  # count=28, max_id=4435, L_id=1090, R_id=4435
    (b' Ed', b'en', b' Eden'),  # count=46, max_id=4477, L_id=4477, R_id=269
    (b'rig', b'ida', b'rigida'),  # count=25, max_id=4497, L_id=2610, R_id=4497
    (b'ida', b'ire', b'idaire'),  # count=25, max_id=4497, L_id=4497, R_id=598
    (b' Har', b'b', b' Harb'),  # count=76, max_id=4840, L_id=4840, R_id=98
    (b' W', b'orms', b' Worms'),  # count=33, max_id=4853, L_id=373, R_id=4853
    (b' Cor', b'ner', b' Corner'),  # count=31, max_id=4885, L_id=4885, R_id=1354
    (b' spin', b'ner', b' spinner'),  # count=28, max_id=4913, L_id=4913, R_id=1354
    (b' Th', b'irds', b' Thirds'),  # count=25, max_id=4994, L_id=1223, R_id=4994
    (b' E', b'ND', b' END'),  # count=49, max_id=5093, L_id=453, R_id=5093
    (b' aer', b'on', b' aeron'),  # count=34, max_id=5118, L_id=5118, R_id=261
    (b' pin', b'n', b' pinn'),  # count=31, max_id=5142, L_id=5142, R_id=110
    (b' e', b'igen', b' eigen'),  # count=118, max_id=5177, L_id=298, R_id=5177
    (b'igen', b've', b'igenve'),  # count=76, max_id=5177, L_id=5177, R_id=301
    (b'oon', b'otic', b'oonotic'),  # count=47, max_id=5188, L_id=2888, R_id=5188
    (b' Power', b'ball', b' Powerball'),  # count=28, max_id=5194, L_id=5194, R_id=3408
    (b' \\', b'[', b' \\['),  # count=26, max_id=5245, L_id=5245, R_id=91
    (b' shar', b'ara', b' sharara'),  # count=25, max_id=5361, L_id=3593, R_id=5361
    (b'arn', b'ley', b'arnley'),  # count=55, max_id=5405, L_id=5405, R_id=2745
    (b' D', b'arn', b' Darn'),  # count=51, max_id=5405, L_id=427, R_id=5405
    (b' L', b'iber', b' Liber'),  # count=24, max_id=5503, L_id=491, R_id=5503
    (b'H', b'US', b'HUS'),  # count=27, max_id=5534, L_id=72, R_id=5534
    (b'ay', b'ama', b'ayama'),  # count=57, max_id=5535, L_id=341, R_id=5535
    (b'oys', b'ia', b'oysia'),  # count=163, max_id=5570, L_id=5570, R_id=604
    (b' Z', b'oys', b' Zoys'),  # count=135, max_id=5570, L_id=2012, R_id=5570
    (b' z', b'oys', b' zoys'),  # count=37, max_id=5570, L_id=1706, R_id=5570
    (b' mir', b'r', b' mirr'),  # count=25, max_id=5598, L_id=5598, R_id=114
    (b' ', b'].', b' ].'),  # count=26, max_id=5649, L_id=32, R_id=5649
    (b'||', b'=', b'||='),  # count=200, max_id=5710, L_id=5710, R_id=61
    (b'=', b'||', b'=||'),  # count=200, max_id=5710, L_id=61, R_id=5710
    (b'||', b'\xe2', b'||\xe2'),  # count=25, max_id=5710, L_id=5710, R_id=226
    (b' end', b'point', b' endpoint'),  # count=26, max_id=5739, L_id=1118, R_id=5739
    (b' Re', b'vit', b' Revit'),  # count=30, max_id=5762, L_id=1673, R_id=5762
    (b' Ob', b't', b' Obt'),  # count=51, max_id=5841, L_id=5841, R_id=116
    (b' fan', b'ner', b' fanner'),  # count=33, max_id=5883, L_id=5883, R_id=1354
    (b'if', b'eren', b'iferen'),  # count=36, max_id=5932, L_id=345, R_id=5932
    (b'ut', b'roph', b'utroph'),  # count=31, max_id=5951, L_id=316, R_id=5951
    (b'roph', b'ication', b'rophication'),  # count=30, max_id=5951, L_id=5951, R_id=1736
    (b'cher', b'ry', b'cherry'),  # count=26, max_id=5978, L_id=5978, R_id=523
    (b' lock', b'er', b' locker'),  # count=28, max_id=5998, L_id=5998, R_id=263
    (b' sen', b'es', b' senes'),  # count=78, max_id=6112, L_id=6112, R_id=268
    (b' Def', b'ender', b' Defender'),  # count=25, max_id=6160, L_id=6160, R_id=3669
    (b'Le', b'aks', b'Leaks'),  # count=24, max_id=6261, L_id=6261, R_id=3018
    (b' Both', b'well', b' Bothwell'),  # count=60, max_id=6436, L_id=4990, R_id=6436
    (b'w', b'atching', b'watching'),  # count=30, max_id=6508, L_id=119, R_id=6508
    (b'ing', b'you', b'ingyou'),  # count=90, max_id=6534, L_id=272, R_id=6534
    (b'tt', b'or', b'ttor'),  # count=58, max_id=6761, L_id=6761, R_id=276
    (b'ure', b'tt', b'urett'),  # count=40, max_id=6761, L_id=367, R_id=6761
    (b'osaur', b'iform', b'osauriform'),  # count=30, max_id=6777, L_id=6777, R_id=5915
    (b' arch', b'osaur', b' archosaur'),  # count=28, max_id=6777, L_id=3372, R_id=6777
    (b' Equ', b'ations', b' Equations'),  # count=31, max_id=6878, L_id=6878, R_id=545
    (b' Sil', b'ent', b' Silent'),  # count=34, max_id=6884, L_id=6884, R_id=299
    (b' crack', b'ling', b' crackling'),  # count=41, max_id=7122, L_id=7122, R_id=1413
    (b' invent', b'ors', b' inventors'),  # count=25, max_id=7169, L_id=7169, R_id=581
    (b'cal', b'cul', b'calcul'),  # count=38, max_id=7462, L_id=7462, R_id=1763
    (b' Bre', b'ville', b' Breville'),  # count=26, max_id=7561, L_id=6018, R_id=7561
    (b' M', b'ega', b' Mega'),  # count=32, max_id=7728, L_id=404, R_id=7728
    (b' Mill', b'ions', b' Millions'),  # count=29, max_id=7836, L_id=7836, R_id=462
    (b'des', b'cript', b'descript'),  # count=25, max_id=7851, L_id=5261, R_id=7851
    (b' Bu', b'cc', b' Bucc'),  # count=27, max_id=8056, L_id=8056, R_id=529
    (b' Ap', b'o', b' Apo'),  # count=31, max_id=8109, L_id=8109, R_id=111
    (b'orph', b'oph', b'orphoph'),  # count=70, max_id=8120, L_id=8120, R_id=2949
    (b' Am', b'orph', b' Amorph'),  # count=48, max_id=8120, L_id=2852, R_id=8120
    (b'c', b'utter', b'cutter'),  # count=28, max_id=8149, L_id=99, R_id=8149
    (b'pert', b'ures', b'pertures'),  # count=28, max_id=8150, L_id=8150, R_id=907
    (b' a', b'pert', b' apert'),  # count=27, max_id=8150, L_id=257, R_id=8150
    (b' Star', b'fish', b' Starfish'),  # count=28, max_id=8287, L_id=8287, R_id=3805
    (b' por', b'ridge', b' porridge'),  # count=37, max_id=8343, L_id=8343, R_id=5810
    (b'gar', b'ita', b'garita'),  # count=35, max_id=8458, L_id=2306, R_id=8458
    (b'":', b'[', b'":['),  # count=35, max_id=8473, L_id=8473, R_id=91
    (b' magnet', b'ite', b' magnetite'),  # count=38, max_id=8502, L_id=8502, R_id=602
    (b' E', b'RA', b' ERA'),  # count=32, max_id=8538, L_id=453, R_id=8538
    (b' condens', b'ate', b' condensate'),  # count=24, max_id=8565, L_id=8565, R_id=372
    (b' D', b'MA', b' DMA'),  # count=132, max_id=8570, L_id=427, R_id=8570
    (b'B', b'EG', b'BEG'),  # count=37, max_id=8681, L_id=66, R_id=8681
    (b' Elect', b'romagnetic', b' Electromagnetic'),  # count=26, max_id=8782, L_id=4616, R_id=8782
    (b' Squ', b'id', b' Squid'),  # count=35, max_id=8967, L_id=8967, R_id=320
    (b' shape', b'wear', b' shapewear'),  # count=37, max_id=9016, L_id=2607, R_id=9016
    (b'n', b'umbers', b'numbers'),  # count=27, max_id=9027, L_id=110, R_id=9027
    (b' Poly', b'ph', b' Polyph'),  # count=37, max_id=9160, L_id=9160, R_id=759
    (b' Heart', b's', b' Hearts'),  # count=38, max_id=9199, L_id=9199, R_id=115
    (b' quarter', b'back', b' quarterback'),  # count=27, max_id=9240, L_id=9240, R_id=3166
    (b' K', b'HS', b' KHS'),  # count=26, max_id=9261, L_id=776, R_id=9261
    (b'es', b'cence', b'escence'),  # count=51, max_id=9343, L_id=268, R_id=9343
    (b' CR', b'U', b' CRU'),  # count=44, max_id=9465, L_id=9465, R_id=85
    (b' j', b'ello', b' jello'),  # count=51, max_id=9624, L_id=525, R_id=9624
    (b' cro', b'pped', b' cropped'),  # count=59, max_id=9665, L_id=9665, R_id=3833
    (b' cro', b'ft', b' croft'),  # count=26, max_id=9665, L_id=9665, R_id=817
    (b' descript', b'or', b' descriptor'),  # count=93, max_id=9769, L_id=9769, R_id=276
    (b' N', b'FC', b' NFC'),  # count=31, max_id=9787, L_id=489, R_id=9787
    (b'uct', b'ive', b'uctive'),  # count=54, max_id=9902, L_id=9902, R_id=388
    (b'ed', b'uct', b'educt'),  # count=33, max_id=9902, L_id=284, R_id=9902
    (b' Ind', b'uction', b' Induction'),  # count=28, max_id=10015, L_id=1680, R_id=10015
    (b'ru', b'plex', b'ruplex'),  # count=34, max_id=10262, L_id=520, R_id=10262
    (b' Eth', b'an', b' Ethan'),  # count=25, max_id=10338, L_id=10338, R_id=281
    (b' Sc', b'orp', b' Scorp'),  # count=25, max_id=10358, L_id=1396, R_id=10358
    (b'\xc3\xb6', b'go', b'\xc3\xb6go'),  # count=27, max_id=10387, L_id=10387, R_id=2763
    (b' l', b'ords', b' lords'),  # count=28, max_id=10468, L_id=300, R_id=10468
    (b'K', b'EA', b'KEA'),  # count=26, max_id=10483, L_id=75, R_id=10483
    (b' jack', b'pot', b' jackpot'),  # count=34, max_id=10530, L_id=6839, R_id=10530
    (b'ash', b'tra', b'ashtra'),  # count=27, max_id=10581, L_id=1207, R_id=10581
    (b' Po', b'ise', b' Poise'),  # count=25, max_id=10694, L_id=10694, R_id=765
    (b' give', b'away', b' giveaway'),  # count=45, max_id=10991, L_id=1612, R_id=10991
    (b' R', b'acer', b' Racer'),  # count=26, max_id=11103, L_id=468, R_id=11103
    (b' heart', b'fire', b' heartfire'),  # count=31, max_id=11186, L_id=1898, R_id=11186
    (b' ech', b'in', b' echin'),  # count=37, max_id=11299, L_id=11299, R_id=258
    (b'op', b'rene', b'oprene'),  # count=80, max_id=11355, L_id=394, R_id=11355
    (b' Church', b'ill', b' Churchill'),  # count=32, max_id=11471, L_id=11471, R_id=371
    (b' Direct', b'X', b' DirectX'),  # count=34, max_id=11570, L_id=11570, R_id=88
    (b' Ven', b'et', b' Venet'),  # count=26, max_id=11585, L_id=11585, R_id=310
    (b' Tri', b'angle', b' Triangle'),  # count=69, max_id=11652, L_id=11652, R_id=6460
    (b' SD', b'R', b' SDR'),  # count=35, max_id=11918, L_id=11918, R_id=82
    (b'}', b'_{', b'}_{'),  # count=26, max_id=11923, L_id=125, R_id=11923
    (b' key', b'log', b' keylog'),  # count=27, max_id=12016, L_id=1604, R_id=12016
    (b' unf', b'olding', b' unfolding'),  # count=32, max_id=12032, L_id=6377, R_id=12032
    (b'/', b'stock', b'/stock'),  # count=55, max_id=12180, L_id=47, R_id=12180
    (b' coll', b'ateral', b' collateral'),  # count=25, max_id=12283, L_id=2132, R_id=12283
    (b' b', b'iped', b' biped'),  # count=25, max_id=12501, L_id=277, R_id=12501
    (b'i', b'ensis', b'iensis'),  # count=41, max_id=12664, L_id=105, R_id=12664
    (b' bi', b'osphere', b' biosphere'),  # count=32, max_id=12775, L_id=1381, R_id=12775
    (b' P', b'odge', b' Podge'),  # count=43, max_id=12920, L_id=403, R_id=12920
    (b'ussion', b'ex', b'ussionex'),  # count=25, max_id=13033, L_id=13033, R_id=1375
    (b' Tri', b'angles', b' Triangles'),  # count=25, max_id=13349, L_id=11652, R_id=13349
    (b'igen', b'value', b'igenvalue'),  # count=40, max_id=13584, L_id=5177, R_id=13584
    (b' H', b'OG', b' HOG'),  # count=32, max_id=13632, L_id=431, R_id=13632
    (b' quartz', b'ite', b' quartzite'),  # count=25, max_id=13756, L_id=13756, R_id=602
    (b' Milk', b'weed', b' Milkweed'),  # count=82, max_id=13813, L_id=13813, R_id=8545
    (b' N', b'FR', b' NFR'),  # count=28, max_id=13886, L_id=489, R_id=13886
    (b'pan', b'osomes', b'panosomes'),  # count=31, max_id=14080, L_id=3841, R_id=14080
    (b'vet', b'tes', b'vettes'),  # count=66, max_id=14154, L_id=14154, R_id=3872
    (b'vet', b'te', b'vette'),  # count=47, max_id=14154, L_id=14154, R_id=675
    (b' Sh', b'ui', b' Shui'),  # count=35, max_id=14265, L_id=1607, R_id=14265
    (b' phyl', b'um', b' phylum'),  # count=28, max_id=14430, L_id=14430, R_id=375
    (b' pand', b'emics', b' pandemics'),  # count=25, max_id=14514, L_id=6531, R_id=14514
    (b'mus', b'ic', b'music'),  # count=27, max_id=14568, L_id=14568, R_id=290
    (b'L', b'isa', b'Lisa'),  # count=31, max_id=14769, L_id=76, R_id=14769
    (b'mi', b'ere', b'miere'),  # count=32, max_id=14784, L_id=14784, R_id=504
    (b' Pre', b'mi', b' Premi'),  # count=31, max_id=14784, L_id=2908, R_id=14784
    (b'\xef\xbf\xbd\xef\xbf\xbd', b'\xef\xbf\xbd\xef\xbf\xbd', b'\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd'),  # count=42, max_id=14789, L_id=14789, R_id=14789
    (b'\xef\xbf\xbd\xef\xbf\xbd', b'\xef\xbf\xbd', b'\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd'),  # count=32, max_id=14789, L_id=14789, R_id=8225
    (b' \xc2\xbb', b'\n\n', b' \xc2\xbb\n\n'),  # count=150, max_id=14999, L_id=14999, R_id=360
    (b' bare', b'foot', b' barefoot'),  # count=26, max_id=15044, L_id=7833, R_id=15044
    (b' lap', b'ar', b' lapar'),  # count=30, max_id=15165, L_id=15165, R_id=286
    (b' gamb', b'ien', b' gambien'),  # count=30, max_id=15475, L_id=15475, R_id=1093
    (b' exh', b'ale', b' exhale'),  # count=30, max_id=15756, L_id=15756, R_id=1084
    (b' cat', b'amar', b' catamar'),  # count=78, max_id=15912, L_id=1095, R_id=15912
    (b'amar', b'an', b'amaran'),  # count=49, max_id=15912, L_id=15912, R_id=281
    (b'amar', b'ans', b'amarans'),  # count=42, max_id=15912, L_id=15912, R_id=512
    (b' Od', b'ds', b' Odds'),  # count=50, max_id=16307, L_id=16307, R_id=995
    (b' ES', b'R', b' ESR'),  # count=25, max_id=16486, L_id=16486, R_id=82
    (b' Ba', b'iley', b' Bailey'),  # count=26, max_id=16753, L_id=14362, R_id=16753
    (b'th', b'olin', b'tholin'),  # count=27, max_id=16994, L_id=385, R_id=16994
    (b' E', b'urop', b' Europ'),  # count=25, max_id=17052, L_id=453, R_id=17052
    (b' vest', b'ig', b' vestig'),  # count=44, max_id=17180, L_id=17180, R_id=325
    (b'_', b'plan', b'_plan'),  # count=34, max_id=17226, L_id=95, R_id=17226
    (b' Bron', b'cos', b' Broncos'),  # count=38, max_id=17520, L_id=17520, R_id=9788
    (b' T', b'rout', b' Trout'),  # count=31, max_id=17590, L_id=319, R_id=17590
    (b'ination', b'number', b'inationnumber'),  # count=25, max_id=17659, L_id=1436, R_id=17659
    (b' subtract', b'er', b' subtracter'),  # count=41, max_id=17734, L_id=17734, R_id=263
    (b'.d', b'est', b'.dest'),  # count=25, max_id=18127, L_id=18127, R_id=350
    (b' exempl', b'ary', b' exemplary'),  # count=26, max_id=18144, L_id=18144, R_id=586
    (b' l', b'uther', b' luther'),  # count=28, max_id=18336, L_id=300, R_id=18336
    (b' Ah', b'm', b' Ahm'),  # count=26, max_id=18356, L_id=18356, R_id=109
    (b' adsor', b'b', b' adsorb'),  # count=38, max_id=18757, L_id=18757, R_id=98
    (b' slipp', b'age', b' slippage'),  # count=37, max_id=18821, L_id=18821, R_id=485
    (b' v', b'oter', b' voter'),  # count=27, max_id=19014, L_id=392, R_id=19014
    (b' Spl', b'it', b' Split'),  # count=26, max_id=19420, L_id=19420, R_id=273
    (b' antiv', b'irus', b' antivirus'),  # count=31, max_id=19454, L_id=19454, R_id=5531
    (b' Sequ', b'ence', b' Sequence'),  # count=39, max_id=19523, L_id=19523, R_id=567
    (b' Cu', b'vet', b' Cuvet'),  # count=27, max_id=19606, L_id=19606, R_id=14154
    (b' GL', b'M', b' GLM'),  # count=26, max_id=19685, L_id=19685, R_id=77
    (b' smart', b'watch', b' smartwatch'),  # count=27, max_id=19877, L_id=3773, R_id=19877
    (b' ab', b'alone', b' abalone'),  # count=40, max_id=19881, L_id=447, R_id=19881
    (b' UT', b'Is', b' UTIs'),  # count=25, max_id=19962, L_id=19962, R_id=2982
    (b' fork', b'lift', b' forklift'),  # count=29, max_id=20003, L_id=12111, R_id=20003
    (b' aeros', b'ols', b' aerosols'),  # count=25, max_id=20099, L_id=20099, R_id=11820
    (b'bas', b'a', b'basa'),  # count=30, max_id=20414, L_id=20414, R_id=97
    (b'iel', b'bas', b'ielbas'),  # count=28, max_id=20414, L_id=1137, R_id=20414
    (b'chin', b'acea', b'chinacea'),  # count=31, max_id=20512, L_id=20512, R_id=19935
    (b' E', b'chin', b' Echin'),  # count=26, max_id=20512, L_id=453, R_id=20512
    (b'eren', b'cia', b'erencia'),  # count=36, max_id=20626, L_id=5932, R_id=20626
    (b'igens', b'pace', b'igenspace'),  # count=25, max_id=20714, L_id=20714, R_id=10095
    (b' ach', b'illes', b' achilles'),  # count=30, max_id=20866, L_id=2015, R_id=20866
    (b' Lot', b'tery', b' Lottery'),  # count=58, max_id=21329, L_id=21329, R_id=7120
    (b'CD', b'ATA', b'CDATA'),  # count=31, max_id=21473, L_id=6932, R_id=21473
    (b' D', b'ollar', b' Dollar'),  # count=30, max_id=21601, L_id=427, R_id=21601
    (b' Dys', b'on', b' Dyson'),  # count=25, max_id=21617, L_id=21617, R_id=261
    (b' H', b'GH', b' HGH'),  # count=25, max_id=21849, L_id=431, R_id=21849
    (b'oph', b'agy', b'ophagy'),  # count=305, max_id=21893, L_id=2949, R_id=21893
    (b' R', b'attlesn', b' Rattlesn'),  # count=26, max_id=22340, L_id=468, R_id=22340
    (b' l', b'arynx', b' larynx'),  # count=27, max_id=22660, L_id=300, R_id=22660
    (b' B', b'acillus', b' Bacillus'),  # count=33, max_id=22708, L_id=408, R_id=22708
    (b' Hood', b'ie', b' Hoodie'),  # count=53, max_id=23053, L_id=23053, R_id=549
    (b' hamm', b'ers', b' hammers'),  # count=32, max_id=23061, L_id=23061, R_id=378
    (b'\xec\x9d', b'\xb4', b'\xec\x9d\xb4'),  # count=29, max_id=23136, L_id=23136, R_id=180
    (b' alb', b'icans', b' albicans'),  # count=25, max_id=23216, L_id=9509, R_id=23216
    (b' Croc', b's', b' Crocs'),  # count=65, max_id=23250, L_id=23250, R_id=115
    (b'on', b'autical', b'onautical'),  # count=29, max_id=23484, L_id=261, R_id=23484
    (b' T', b'ango', b' Tango'),  # count=32, max_id=23499, L_id=319, R_id=23499
    (b'iped', b'alism', b'ipedalism'),  # count=27, max_id=23545, L_id=12501, R_id=23545
    (b' eggs', b'hells', b' eggshells'),  # count=39, max_id=23634, L_id=2843, R_id=23634
    (b' Invent', b'ory', b' Inventory'),  # count=86, max_id=23759, L_id=23759, R_id=695
    (b' deduct', b'ive', b' deductive'),  # count=42, max_id=23826, L_id=23826, R_id=388
    (b' Tun', b'nel', b' Tunnel'),  # count=28, max_id=23856, L_id=23856, R_id=6497
    (b'amic', b'oco', b'amicoco'),  # count=26, max_id=24000, L_id=6951, R_id=24000
    (b' carbure', b'tt', b' carburett'),  # count=39, max_id=24125, L_id=24125, R_id=6761
    (b' Sum', b'atra', b' Sumatra'),  # count=49, max_id=24262, L_id=6362, R_id=24262
    (b' anth', b'ocyan', b' anthocyan'),  # count=102, max_id=24475, L_id=18948, R_id=24475
    (b'ocyan', b'in', b'ocyanin'),  # count=61, max_id=24475, L_id=24475, R_id=258
    (b'ocyan', b'ins', b'ocyanins'),  # count=46, max_id=24475, L_id=24475, R_id=901
    (b' appra', b'iser', b' appraiser'),  # count=26, max_id=24494, L_id=24494, R_id=10151
    (b' cuff', b'links', b' cufflinks'),  # count=29, max_id=24619, L_id=21814, R_id=24619
    (b'####', b'####', b'########'),  # count=78, max_id=24632, L_id=24632, R_id=24632
    (b' poth', b'os', b' pothos'),  # count=67, max_id=24793, L_id=24793, R_id=399
    (b' Py', b'rex', b' Pyrex'),  # count=58, max_id=24803, L_id=12461, R_id=24803
    (b' infl', b'orescence', b' inflorescence'),  # count=31, max_id=24943, L_id=3439, R_id=24943
    (b' Horn', b'bill', b' Hornbill'),  # count=30, max_id=25047, L_id=22774, R_id=25047
    (b' lys', b'ine', b' lysine'),  # count=49, max_id=25057, L_id=25057, R_id=451
    (b' Emer', b'ald', b' Emerald'),  # count=49, max_id=25059, L_id=25059, R_id=9839
    (b'iss', b'erie', b'isserie'),  # count=32, max_id=25081, L_id=879, R_id=25081
    (b'op', b'ithe', b'opithe'),  # count=51, max_id=25139, L_id=394, R_id=25139
    (b'ithe', b'cus', b'ithecus'),  # count=27, max_id=25139, L_id=25139, R_id=23582
    (b'ithe', b'c', b'ithec'),  # count=24, max_id=25139, L_id=25139, R_id=99
    (b' choke', b'cher', b' chokecher'),  # count=25, max_id=25345, L_id=25345, R_id=5978
    (b' Brow', b'ns', b' Browns'),  # count=38, max_id=25787, L_id=25787, R_id=444
    (b' orangut', b'ans', b' orangutans'),  # count=26, max_id=25925, L_id=25925, R_id=512
    (b' chis', b'el', b' chisel'),  # count=26, max_id=26147, L_id=26147, R_id=336
    (b'Ren', b'ewable', b'Renewable'),  # count=26, max_id=26206, L_id=26206, R_id=19187
    (b' Scandinav', b'ian', b' Scandinavian'),  # count=27, max_id=26231, L_id=26231, R_id=940
    (b' Im', b'plementation', b' Implementation'),  # count=33, max_id=26252, L_id=2163, R_id=26252
    (b' Inform', b'al', b' Informal'),  # count=43, max_id=26590, L_id=26590, R_id=280
    (b' ging', b'ivitis', b' gingivitis'),  # count=24, max_id=26640, L_id=26640, R_id=17701
    (b' rattlesn', b'ake', b' rattlesnake'),  # count=31, max_id=26734, L_id=26734, R_id=665
    (b' rattlesn', b'akes', b' rattlesnakes'),  # count=28, max_id=26734, L_id=26734, R_id=1468
    (b'oss', b'amer', b'ossamer'),  # count=53, max_id=26769, L_id=756, R_id=26769
    (b' cl', b'inker', b' clinker'),  # count=41, max_id=27025, L_id=528, R_id=27025
    (b' Cross', b'Fit', b' CrossFit'),  # count=31, max_id=27527, L_id=9854, R_id=27527
    (b' LI', b'KE', b' LIKE'),  # count=30, max_id=27890, L_id=27890, R_id=15030
    (b' Corp', b'se', b' Corpse'),  # count=30, max_id=28329, L_id=28329, R_id=344
    (b' prem', b'iere', b' premiere'),  # count=41, max_id=28851, L_id=5111, R_id=28851
    (b' Amend', b'ment', b' Amendment'),  # count=27, max_id=29156, L_id=29156, R_id=390
    (b' L', b'otto', b' Lotto'),  # count=27, max_id=29404, L_id=491, R_id=29404
    (b' flow', b'chart', b' flowchart'),  # count=38, max_id=29468, L_id=1284, R_id=29468
    (b' off', b'season', b' offseason'),  # count=29, max_id=29659, L_id=703, R_id=29659
    (b' neurodeg', b'enerative', b' neurodegenerative'),  # count=25, max_id=29863, L_id=29863, R_id=12765
    (b' til', b'apia', b' tilapia'),  # count=35, max_id=29977, L_id=18221, R_id=29977
    (b' Benn', b'ett', b' Bennett'),  # count=34, max_id=30230, L_id=30230, R_id=9570
    (b' Far', b'aday', b' Faraday'),  # count=40, max_id=30276, L_id=12476, R_id=30276
    (b'f', b'avorite', b'favorite'),  # count=37, max_id=30495, L_id=102, R_id=30495
    (b' amb', b'ulance', b' ambulance'),  # count=28, max_id=30714, L_id=5815, R_id=30714
    (b' avalan', b'che', b' avalanche'),  # count=43, max_id=30789, L_id=30789, R_id=4095
    (b' Pro', b'bability', b' Probability'),  # count=56, max_id=30969, L_id=1121, R_id=30969
    (b' poly', b'carbonate', b' polycarbonate'),  # count=24, max_id=31022, L_id=3035, R_id=31022
    (b' air', b'foil', b' airfoil'),  # count=44, max_id=31060, L_id=968, R_id=31060
    (b' Hib', b'iscus', b' Hibiscus'),  # count=39, max_id=31068, L_id=31068, R_id=19146
    (b'corrh', b'iz', b'corrhiz'),  # count=32, max_id=31418, L_id=31418, R_id=484
    (b' my', b'corrh', b' mycorrh'),  # count=28, max_id=31418, L_id=777, R_id=31418
    (b' Armen', b'ian', b' Armenian'),  # count=31, max_id=31637, L_id=31637, R_id=940
    (b' Neigh', b'bor', b' Neighbor'),  # count=26, max_id=31641, L_id=31641, R_id=3666
    (b'appear', b'ance', b'appearance'),  # count=42, max_id=31768, L_id=31768, R_id=532
    (b' spect', b'rophot', b' spectrophot'),  # count=34, max_id=31984, L_id=3968, R_id=31984
    (b'rophot', b'ometer', b'rophotometer'),  # count=27, max_id=31984, L_id=31984, R_id=6774
    (b' Z', b'imbabwe', b' Zimbabwe'),  # count=32, max_id=32186, L_id=2012, R_id=32186
    (b' cu', b'vet', b' cuvet'),  # count=74, max_id=32192, L_id=32192, R_id=14154
    (b'oblast', b'oma', b'oblastoma'),  # count=32, max_id=32595, L_id=32595, R_id=4238
    (b' abn', b'ormality', b' abnormality'),  # count=65, max_id=32649, L_id=21569, R_id=32649
]
