"""Auto-generated pass-2 candidate list — coverage-gain pairs (KEEP p1>0 + all FLAGs)
for the held-out-Pareto build-up. DO NOT edit by hand; regenerate with
`uv run python -m tools.gen_pass2_candidates`. Comment = original deltas + source/verdict.
"""

CANDIDATES_PASS2: list[tuple[str, str]] = [
    ('ck', 'er'),  # R3 FLAG p1+4 comp+17
    ('ard', 'ed'),  # R3 FLAG p1+3 comp+23
    ('ot', 'ting'),  # R3 KEEP p1+2 comp-12
    ('ough', 'ly'),  # R3 KEEP p1+2 comp-12
    ('ay', 'ing'),  # R3 KEEP p1+2 comp-10
    ('aps', 'es'),  # R3 KEEP p1+2 comp-8
    ('ct', 'uary'),  # R3 FLAG p1+2 comp+1
    ('zym', 'es'),  # R3 FLAG p1+2 comp+3
    ('n', 'ter'),  # R3 FLAG p1+2 comp+4
    ('ogene', 'ous'),  # R3 FLAG p1+2 comp+6
    ('ick', 'er'),  # R3 FLAG p1+2 comp+7
    ('ig', 'er'),  # R3 FLAG p1+2 comp+10
    ('ush', 'ing'),  # R3 FLAG p1+2 comp+11
    ('pe', 'cial'),  # R3 FLAG p1+2 comp+13
    ('pe', 'cies'),  # R3 FLAG p1+2 comp+15
    ('ort', 'ed'),  # R3 FLAG p1+2 comp+22
    ('il', 'er'),  # R3 FLAG p1+2 comp+22
    ('it', 'ting'),  # R3 FLAG p1+2 comp+27
    ('ak', 'ed'),  # R3 FLAG p1+2 comp+40
    ('it', 'ter'),  # R3 FLAG p1+2 comp+43
    ('il', 'ing'),  # R3 FLAG p1+2 comp+73
    ('u', 'ber'),  # R3 KEEP p1+1 comp-42
    ('ite', 'ly'),  # R3 KEEP p1+1 comp-20
    ('em', 'ically'),  # R1 KEEP p1+1 comp-11
    ('aw', 'ning'),  # R3 KEEP p1+1 comp-9
    ('lish', 'ing'),  # R3 KEEP p1+1 comp-9
    ('ware', 'ness'),  # R1 KEEP p1+1 comp-7
    ('atter', 'ing'),  # R3 KEEP p1+1 comp-6
    ('ent', 'ation'),  # R2 KEEP p1+1 comp-4
    ('ature', 'd'),  # R3 KEEP p1+1 comp-4
    ('ment', 'ation'),  # R2 KEEP p1+1 comp-3
    ('un', 'ning'),  # R3 KEEP p1+1 comp-3
    ('oad', 'ing'),  # R3 KEEP p1+1 comp-3
    ('ull', 'ing'),  # R3 KEEP p1+1 comp-3
    ('ert', 'ation'),  # R2 KEEP p1+1 comp-2
    ('l', 'ation'),  # R2 KEEP p1+1 comp-2
    ('il', 'ting'),  # R3 KEEP p1+1 comp-2
    ('oot', 'ing'),  # R3 KEEP p1+1 comp-2
    ('ire', 'ments'),  # R3 KEEP p1+1 comp-2
    ('ruct', 'or'),  # R3 KEEP p1+1 comp-2
    ('it', 'ness'),  # R1 KEEP p1+1 comp-1
    ('or', 'ation'),  # R2 KEEP p1+1 comp-1
    ('or', 'ious'),  # R3 KEEP p1+1 comp-1
    ('row', 'ning'),  # R3 KEEP p1+1 comp-1
    ('ress', 'or'),  # R3 KEEP p1+1 comp-1
    ('ns', 'ure'),  # R3 KEEP p1+1 comp-1
    ('ud', 'ding'),  # R3 KEEP p1+1 comp-1
    ('r', 'ically'),  # R1 KEEP p1+1 comp+0
    ('ar', 'king'),  # R3 KEEP p1+1 comp+0
    ('ig', 'ers'),  # R3 KEEP p1+1 comp+0
    ('ient', 'ed'),  # R3 KEEP p1+1 comp+0
    ('tain', 'ment'),  # R3 KEEP p1+1 comp+0
    ('icular', 'ly'),  # R3 KEEP p1+1 comp+0
    ('umin', 'ous'),  # R3 KEEP p1+1 comp+0
    ('if', 'ter'),  # R3 KEEP p1+1 comp+0
    ('il', 'ant'),  # R3 KEEP p1+1 comp+0
    ('il', 'ian'),  # R3 KEEP p1+1 comp+0
    ('ut', 'ational'),  # R3 KEEP p1+1 comp+0
    ('ist', 'ication'),  # R3 KEEP p1+1 comp+0
    ('orn', 'ings'),  # R3 KEEP p1+1 comp+0
    ('ort', 'ment'),  # R3 KEEP p1+1 comp+0
    ('ung', 'ent'),  # R3 FLAG p1+1 comp+1
    ('ict', 'ed'),  # R3 FLAG p1+1 comp+1
    ('ellig', 'ent'),  # R3 FLAG p1+1 comp+1
    ('erent', 'ial'),  # R3 FLAG p1+1 comp+1
    ('mit', 'ting'),  # R3 FLAG p1+1 comp+1
    ('ient', 'ial'),  # R3 FLAG p1+1 comp+1
    ('ri', 'ors'),  # R3 FLAG p1+1 comp+1
    ('oubted', 'ly'),  # R1 FLAG p1+1 comp+2
    ('ot', 'hes'),  # R3 FLAG p1+1 comp+2
    ('ri', 'or'),  # R3 FLAG p1+1 comp+2
    ('ag', 'ues'),  # R3 FLAG p1+1 comp+2
    ('duc', 'ers'),  # R3 FLAG p1+1 comp+2
    ('enn', 'ial'),  # R3 FLAG p1+1 comp+2
    ('uff', 'er'),  # R3 FLAG p1+1 comp+2
    ('at', 'ibility'),  # R1 FLAG p1+1 comp+3
    ('b', 'ability'),  # R1 FLAG p1+1 comp+3
    ('ob', 'ility'),  # R1 FLAG p1+1 comp+3
    ('pret', 'ation'),  # R2 FLAG p1+1 comp+3
    ('orm', 'al'),  # R3 FLAG p1+1 comp+3
    ('ight', 'ly'),  # R3 FLAG p1+1 comp+3
    ('erson', 'al'),  # R3 FLAG p1+1 comp+3
    ('oss', 'ing'),  # R3 FLAG p1+1 comp+3
    ('viron', 'ments'),  # R3 FLAG p1+1 comp+3
    ('at', 'ches'),  # R3 FLAG p1+1 comp+4
    ('mit', 'ted'),  # R3 FLAG p1+1 comp+4
    ('am', 'ines'),  # R3 FLAG p1+1 comp+4
    ('ograp', 'hers'),  # R3 FLAG p1+1 comp+4
    ('roubleshoot', 'ing'),  # R3 FLAG p1+1 comp+4
    ('uck', 'er'),  # R3 FLAG p1+1 comp+4
    ('rehens', 'ive'),  # R3 FLAG p1+1 comp+4
    ('ort', 'ing'),  # R3 FLAG p1+1 comp+5
    ('ruct', 'ed'),  # R3 FLAG p1+1 comp+5
    ('erm', 'al'),  # R3 FLAG p1+1 comp+5
    ('if', 'erous'),  # R3 FLAG p1+1 comp+5
    ('in', 'itions'),  # R3 FLAG p1+1 comp+5
    ('ograp', 'her'),  # R3 FLAG p1+1 comp+5
    ('ract', 'ed'),  # R3 FLAG p1+1 comp+5
    ('ract', 'ing'),  # R3 FLAG p1+1 comp+5
    ('inite', 'ly'),  # R3 FLAG p1+1 comp+5
    ('at', 'ched'),  # R3 FLAG p1+1 comp+5
    ('ceed', 'ings'),  # R3 FLAG p1+1 comp+5
    ('ot', 'ation'),  # R2 FLAG p1+1 comp+6
    ('reat', 'ing'),  # R3 FLAG p1+1 comp+6
    ('agnet', 'ism'),  # R3 FLAG p1+1 comp+6
    ('pect', 'ing'),  # R3 FLAG p1+1 comp+6
    ('ard', 'less'),  # R1 FLAG p1+1 comp+7
    ('ios', 'ity'),  # R3 FLAG p1+1 comp+7
    ('ield', 'ing'),  # R3 FLAG p1+1 comp+7
    ('ress', 'es'),  # R3 FLAG p1+1 comp+7
    ('og', 'ging'),  # R3 FLAG p1+1 comp+8
    ('idd', 'ing'),  # R3 FLAG p1+1 comp+8
    ('prising', 'ly'),  # R3 FLAG p1+1 comp+8
    ('ill', 'ation'),  # R2 FLAG p1+1 comp+9
    ('ld', 'er'),  # R3 FLAG p1+1 comp+9
    ('os', 'her'),  # R3 FLAG p1+1 comp+9
    ('arent', 'ly'),  # R3 FLAG p1+1 comp+9
    ('ryst', 'al'),  # R3 FLAG p1+1 comp+9
    ('ick', 'ed'),  # R3 FLAG p1+1 comp+10
    ('uit', 'able'),  # R3 FLAG p1+1 comp+10
    ('ond', 'er'),  # R3 FLAG p1+1 comp+10
    ('at', 'tered'),  # R3 FLAG p1+1 comp+10
    ('cept', 'ive'),  # R3 FLAG p1+1 comp+12
    ('ival', 'ent'),  # R3 FLAG p1+1 comp+12
    ('iver', 'ing'),  # R3 FLAG p1+1 comp+12
    ('omencl', 'ature'),  # R3 FLAG p1+1 comp+12
    ('ong', 'ed'),  # R3 FLAG p1+1 comp+12
    ('or', 'ption'),  # R3 FLAG p1+1 comp+12
    ('umm', 'ies'),  # R3 FLAG p1+1 comp+12
    ('um', 'ption'),  # R3 FLAG p1+1 comp+12
    ('dition', 'ally'),  # R3 FLAG p1+1 comp+12
    ('at', 'hered'),  # R3 FLAG p1+1 comp+13
    ('ens', 'ation'),  # R2 FLAG p1+1 comp+14
    ('ound', 'ed'),  # R3 FLAG p1+1 comp+14
    ('iment', 'ary'),  # R3 FLAG p1+1 comp+14
    ('ud', 'ing'),  # R3 FLAG p1+1 comp+14
    ('imens', 'ions'),  # R3 FLAG p1+1 comp+15
    ('iped', 'es'),  # R3 FLAG p1+1 comp+15
    ('ie', 'wer'),  # R3 FLAG p1+1 comp+15
    ('et', 'ically'),  # R1 FLAG p1+1 comp+16
    ('i', 'ator'),  # R3 FLAG p1+1 comp+16
    ('ent', 'ional'),  # R3 FLAG p1+1 comp+16
    ('ric', 'ted'),  # R3 FLAG p1+1 comp+16
    ('ache', 'lor'),  # R3 FLAG p1+1 comp+16
    ('ick', 'ness'),  # R1 FLAG p1+1 comp+17
    ('ress', 'ing'),  # R3 FLAG p1+1 comp+17
    ('if', 'ted'),  # R3 FLAG p1+1 comp+17
    ('us', 'hed'),  # R3 FLAG p1+1 comp+17
    ('ut', 'ation'),  # R2 FLAG p1+1 comp+19
    ('ruct', 'ive'),  # R3 FLAG p1+1 comp+19
    ('viron', 'ment'),  # R3 FLAG p1+1 comp+19
    ('il', 'ers'),  # R3 FLAG p1+1 comp+20
    ('ogen', 'ous'),  # R3 FLAG p1+1 comp+21
    ('ut', 'her'),  # R3 FLAG p1+1 comp+22
    ('ress', 'ive'),  # R3 FLAG p1+1 comp+23
    ('ound', 'ing'),  # R3 FLAG p1+1 comp+23
    ('ight', 'ing'),  # R3 FLAG p1+1 comp+23
    ('ater', 'nal'),  # R3 FLAG p1+1 comp+23
    ('ew', 'able'),  # R3 FLAG p1+1 comp+24
    ('il', 'ities'),  # R3 FLAG p1+1 comp+25
    ('ry', 'ing'),  # R3 FLAG p1+1 comp+26
    ('um', 'mer'),  # R3 FLAG p1+1 comp+26
    ('erv', 'ing'),  # R3 FLAG p1+1 comp+27
    ('pecial', 'ly'),  # R3 FLAG p1+1 comp+27
    ('ist', 'ically'),  # R1 FLAG p1+1 comp+30
    ('dition', 'al'),  # R3 FLAG p1+1 comp+30
    ('at', 'ically'),  # R1 FLAG p1+1 comp+32
    ('ress', 'ed'),  # R3 FLAG p1+1 comp+34
    ('us', 'ter'),  # R3 FLAG p1+1 comp+41
    ('or', 'ter'),  # R3 FLAG p1+1 comp+41
    ('oid', 'al'),  # R3 FLAG p1+1 comp+42
    ('ig', 'ation'),  # R2 FLAG p1+1 comp+44
    ('il', 'ed'),  # R3 FLAG p1+1 comp+51
    ('orm', 'ality'),  # R3 FLAG p1+1 comp+52
    ('if', 'ting'),  # R3 FLAG p1+1 comp+53
    ('ic', 'king'),  # R3 FLAG p1+1 comp+53
    ('ct', 'ors'),  # R3 FLAG p1+1 comp+54
    ('ri', 'ers'),  # R3 FLAG p1+1 comp+57
    ('oo', 'king'),  # R3 FLAG p1+1 comp+78
    ('oc', 'king'),  # R3 FLAG p1+1 comp+104
]
